
services:
  # Frontend webpage container
  hose-frontend:
    build:
      context: ./frontend
    networks:
      - backend
    depends_on:
      - hose-api

  # Springboot Rest-API container
  hose-api:
    build:
      context: ./server/hose
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hose_db
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      ADMIN_KEY: ${ADMIN_KEY}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    networks:
      - backend

  # Postgres DB container
  postgres:
    build:
      context: ./database 
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  # Flyway service to manage DB and schema
  flyway:
    image: flyway/flyway:10.10.0
    depends_on:
      - postgres
    environment:
      FLYWAY_URL: ${FLYWAY_URL}
      FLYWAY_USER: ${FLYWAY_USER}
      FLYWAY_PASSWORD: ${FLYWAY_PASSWORD}
    command: -connectRetries=10 migrate
    volumes:
      - ./database/migrations:/flyway/sql
    networks:
      - backend

  # Seed DB data first run
  seed-data:
    image: postgres:15
    depends_on:
      flyway:
        condition: service_completed_successfully
    environment:
      PGPASSWORD: ${DB_PASSWORD}
    command: |
      sh -c "
        COUNT=$$(psql -h postgres -U $${DB_USER} -d $${DB_NAME} -t -c 'SELECT COUNT(*) FROM addresses;')
        if [ $$COUNT -eq 0 ]; then
          echo 'Database empty, seeding...'
          psql -h postgres -U $${DB_USER} -d $${DB_NAME} -f /seeds/seed-data.sql
        else
          echo 'Database already seeded, skipping...'
        fi
      "
    volumes:
      - ./database/seeds:/seeds
    networks:
      - backend
  
  # OSRM container to route foot traffic
  osrm-foot:
    image: osrm/osrm-backend
    command: osrm-routed --algorithm mld /data/foot/ellensburg.osrm
    volumes:
      - ./osrm/data:/data
    ports:
      - "5001:5000"
    networks:
      - backend

  # OSRM container to route cycling traffic
  osrm-bike:
    image: osrm/osrm-backend
    command: osrm-routed --algorithm mld /data/bike/ellensburg.osrm
    volumes:
      - ./osrm/data:/data
    ports:
      - "5002:5000"
    networks:
      - backend

  # OSRM container to route vehicle traffic
  osrm-car:
    image: osrm/osrm-backend
    command: osrm-routed --algorithm mld /data/car/ellensburg.osrm
    volumes:
      - ./osrm/data:/data
    ports:
      - "5003:5000"
    networks:
      - backend
  

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:

